export const educationList = [
  { label: 'AS pharmacy technician' },
  { label: 'AS medical laboratory technology'},
  { label: 'AS physical therapy' },
  { label: 'AS health information management'},
  { label: 'AS medical coding' },
  { label: "AS health information technology" },
  { label: 'BSc pharmacy or pharmaceutical sciences' },
  { label: 'BSc exercise science' },
  { label: 'BSc health sciences'},
  { label: 'BSc nutrition and dietetics' },
  { label: 'Bachelor of Arts in healthcare marketing'},
  { label: 'BSc biology' },
  { label: "Bachelor of Science in public health" },
  { label: 'Bachelor of Science in Nursing' },
  { label: 'Bachelor of Science in dental hygiene'},
  { label: 'Bachelor of Science in nuclear medicine technology' },
  { label: 'MS in clinical research'},
  { label: 'MS in speech-language pathology' },
  { label: "MS in healthcare administration" },
  { label: "MS in public health" },
  { label: 'Bachelor of Science in chemistry' },
  { label: 'MS in health information management'},
  { label: 'MS in occupational therapy' },
  { label: 'PhD Physical Therapy'},
  { label: 'MS in nursing administration' },
  { label: "PhD Nursing Science" },
  { label: "PhD Veterinary Medicine" },
  { label: "MS in health sciences" },
  { label: "PhD Pharmacy" },
  { label: "PhD Medicine or PhD Osteopathic Medicine" }
];
